### ISSUE TITLE
Application with KCL native client crash after KCL updated by Go-binary

### ISSUE THREAD

**Issue by bozaro** [kcl-lang/lib#73]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Base reproduce steps:

 - Run long-life application with KCL native client version A;
 - Run some Go-application with KCL version B (`go run kcl-lang.io/cli/cmd/kcl@v0.8.6 version`)
 - Generate some configuration in long-life application. This application will crash.

Vanila tools reproduce steps:

 - Run KCL playground version A (`go run kcl-lang.io/cli/cmd/kcl@v0.8.7 play --addr 127.0.0.1:8080`);
 - Start long-life application with KCL native client (`kclvm`) by click `Run` in playground;
 - Remove file `~/go/bin/kclvm_cli` to avoid `failed: open /home/bozaro/go/bin/kclvm_cli: text file busy` error (native client from base scenario don't use `kclvm_cli`);
 - Install KCL version B by Go application (`go run kcl-lang.io/cli/cmd/kcl@v0.8.6 version`);
 - Click `Run` in playground and see `unexpected EOF` error (`kclvm_cli server` crashed);
 - After some `Run` clicks all old `kclvm_cli server` will crashed and new `kclvm_cli server` will works again.

### 2. What did you expect to see? (Required)

Long-life application still works.

### 3. What did you see instead (Required)

Long-life application crash or became unfuncation state.

### 4. What is your KCL components version? (Required)

All versions.

**Comment by Peefy** [comment]
Amazing Job! Thanks a lot.
